version: "3.2"
services:
    eureka_service:
        build:
            context: ./eureka-service
        container_name: "eureka-service-container"
        ports:
            - "8761:8761"
        networks:
            - eureka_network

    eureka_client:
        build:
            context: ./eureka-client
        container_name: "eureka-client-container"
        ports:
            - "9872:9872"
        depends_on:
            - "eureka_service"
            - "config_server"
        networks:
            - eureka_network

    eureka_feign_client:
        build:
            context: ./eureka-feign-client
        container_name: "eureka-feign-client-container"
        ports:
            - "8190:8190"
        depends_on:
            - "eureka_client"
        networks:
            - eureka_network

    config_server:
        build:
            context: ./config-server
        container_name: "config-server-container"
        ports:
            - "8081:8081"
        depends_on:
            - "eureka_service"
        networks:
            - eureka_network

#    zuul_server:
#        build:
#            context: ./zuul-server
#        container_name: "zuul-server-container"
#        ports:
#            - "5555:5555"
#        depends_on:
#            - "eureka_service"
#        networks:
#            - eureka_network
networks:
    eureka_network:
        name: "eureka_network"
        driver: bridge