spring:
  application:
    name: zuul-server
server:
  port: 5555
  servlet:
    context-path: /cloud
eureka:
#  instance:
#    preferIpAddress: true
#    ip-address: 192.168.31.135
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service-container:8761/eureka/
zuul:
  routes:
    geek-spring-cloud-eureka-client: /gclient/**
    secured-client: /secured/**
    statistic-chain-client: /statistic/**
    secured-feign-client: /feign/**
  sensitiveHeaders: Cookie, Set-Cookie
ribbon:
  ReadTimeout: 60000